inputs:
    dirname: null # leave null if not common for all input files
    filenames: [
        /home/wuct/ALICE/local/Results/checks/ML/inputDistr/input/input_ref/fit/ptSmear_Prompt/rawyield/RawYields_D0_PbPb_0_hist_bkg_ref.root,
        /home/wuct/ALICE/local/Results/checks/ML/inputDistr/input/input_ref/fit/ptSmear1.5_phi_Prompt/rawyield/RawYields_D0_PbPb_0_hist_bkg_ref.root,
        /home/wuct/ALICE/local/Results/checks/ML/inputDistr/input/input_ref/fit/ptSmear_FD/rawyield/RawYields_D0_PbPb_0_hist_bkg_ref.root,
        /home/wuct/ALICE/local/Results/checks/ML/inputDistr/input/input_ref/fit/ptSmear1.5_phi_FD/rawyield/RawYields_D0_PbPb_0_hist_bkg_ref.root,
    ]
    objectnames: [hParamAlpha, hParamAlpha, hParamAlpha, hParamAlpha] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: /home/wuct/ALICE/local/Results/checks/ML/inputDistr/input/input_ref/fit/ParamAlpha_bkg_ref # with path and w/o extension
    extensions: [pdf, root, png] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1., 1., 1., 1., 1., 1., 1., 1.]
    lambdaParams: [1., 1., 1., 1., 1., 1., 1., 1., 1.] # counts -> (counts - 1) * lambda + 1
    normalize: [false, false, false, false, false, false, false, false, false] # divide histogram by its area
    colors: [kRed+1,kBlack,kRed+1,kBlack,   kAzure+47, kOrange+7, kBlack, kBlack, kRed+1, kRed+1, kAzure+4, kGreen+2, kOrange+7, kMagenta+1, kBlue, kCyan+3, kSpring-5]
    markers: [kFullCircle, kFullCircle, kOpenSquare, kOpenSquare, kFullCircle, kFullCircle, kFullCircle, kFullCircle, kFullCircle]
    markersize: 1.5
    linewidth: 3
    fillstyle: [1,1,1,1]
    fillalpha: [1,1,1,1]
    drawopt: [lp, lp, lp, lp, p, p, e, e, e]
    
    ratio: 
        enable: true
        uncertainties:
            enable: false
            corr: false
        displayRMS: false
        multiRatio: true
        indexNumerator: [0, 2]
        indexDenominator: [1, 3]

    errcomp: # comparison of uncertainties
        enable: false
        relative: false
    uncertainty: 
        enable: true

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.2, 0.9]
        ylimits: [0.2, 0.5]
        header: null
        titles: ['Prompt ptSmear', 'Prompt ptSmear1p5 phi', 'FD ptSmear', 'FD ptSmear1p5 phi']
        options: [lp, lp, lp, lp, lp, lp, lp, lp, lp, lp]
        textsize: 0.035
        ncolumns: 2

    text:
        x: [0.5, 0.8]
        y: [0.8, 0.9]
        text: ""
        textsize: 0.03
        textfont: 42
        textalign: 12

    canvas:
        width: 2160
        heigth: 1080
        xaxistitle: '#it{p}_{T} (GeV/#it{c})'
        # yaxistitle: 'Efficiency (w. ptWeights)'
        yaxistitle: 'Signal Parameter alpha'
        # yaxistitle: 'Raw yield'
        xlimits: [0., 24]
        ylimits: [1, 2]
        ylimitsratio: [0.6,  1.4]
        ylimitserr: [0., 0.35]
        logy: false
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
